// <auto-generated />
using Curso.Repo.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Curso.API.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("Curso.API.Entities.Diretor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Diretores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Steven Spielberg"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Christopher Nolan"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Quentin Tarantino"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Martin Scorsese"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "James Cameron"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Ridley Scott"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Peter Jackson"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Tim Burton"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Clint Eastwood"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "David Fincher"
                        });
                });

            modelBuilder.Entity("Curso.API.Entities.Filme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiretorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiretorId");

                    b.ToTable("Filmes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ano = 2010,
                            DiretorId = 2,
                            Titulo = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            Ano = 2014,
                            DiretorId = 2,
                            Titulo = "Interstellar"
                        },
                        new
                        {
                            Id = 3,
                            Ano = 2017,
                            DiretorId = 2,
                            Titulo = "Dunkirk"
                        },
                        new
                        {
                            Id = 4,
                            Ano = 1994,
                            DiretorId = 3,
                            Titulo = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 5,
                            Ano = 2003,
                            DiretorId = 3,
                            Titulo = "Kill Bill Vol. 1"
                        },
                        new
                        {
                            Id = 6,
                            Ano = 2004,
                            DiretorId = 3,
                            Titulo = "Kill Bill Vol. 2"
                        },
                        new
                        {
                            Id = 7,
                            Ano = 2013,
                            DiretorId = 4,
                            Titulo = "The Wolf of Wall Street"
                        },
                        new
                        {
                            Id = 8,
                            Ano = 1976,
                            DiretorId = 4,
                            Titulo = "Taxi Driver"
                        },
                        new
                        {
                            Id = 9,
                            Ano = 1990,
                            DiretorId = 4,
                            Titulo = "Goodfellas"
                        },
                        new
                        {
                            Id = 10,
                            Ano = 2009,
                            DiretorId = 5,
                            Titulo = "Avatar"
                        },
                        new
                        {
                            Id = 11,
                            Ano = 1997,
                            DiretorId = 5,
                            Titulo = "Titanic"
                        },
                        new
                        {
                            Id = 12,
                            Ano = 1986,
                            DiretorId = 5,
                            Titulo = "Aliens"
                        },
                        new
                        {
                            Id = 13,
                            Ano = 2000,
                            DiretorId = 6,
                            Titulo = "Gladiator"
                        },
                        new
                        {
                            Id = 14,
                            Ano = 1979,
                            DiretorId = 6,
                            Titulo = "Alien"
                        },
                        new
                        {
                            Id = 15,
                            Ano = 1982,
                            DiretorId = 6,
                            Titulo = "Blade Runner"
                        },
                        new
                        {
                            Id = 16,
                            Ano = 2001,
                            DiretorId = 7,
                            Titulo = "The Lord of the Rings: The Fellowship of the Ring"
                        },
                        new
                        {
                            Id = 17,
                            Ano = 2002,
                            DiretorId = 7,
                            Titulo = "The Lord of the Rings: The Two Towers"
                        },
                        new
                        {
                            Id = 18,
                            Ano = 2003,
                            DiretorId = 7,
                            Titulo = "The Lord of the Rings: The Return of the King"
                        },
                        new
                        {
                            Id = 19,
                            Ano = 1990,
                            DiretorId = 8,
                            Titulo = "Edward Scissorhands"
                        },
                        new
                        {
                            Id = 20,
                            Ano = 1988,
                            DiretorId = 8,
                            Titulo = "Beetlejuice"
                        },
                        new
                        {
                            Id = 21,
                            Ano = 1989,
                            DiretorId = 8,
                            Titulo = "Batman"
                        },
                        new
                        {
                            Id = 22,
                            Ano = 2008,
                            DiretorId = 9,
                            Titulo = "Gran Torino"
                        },
                        new
                        {
                            Id = 23,
                            Ano = 2004,
                            DiretorId = 9,
                            Titulo = "Million Dollar Baby"
                        },
                        new
                        {
                            Id = 24,
                            Ano = 1992,
                            DiretorId = 9,
                            Titulo = "Unforgiven"
                        },
                        new
                        {
                            Id = 25,
                            Ano = 1999,
                            DiretorId = 10,
                            Titulo = "Fight Club"
                        },
                        new
                        {
                            Id = 26,
                            Ano = 1995,
                            DiretorId = 10,
                            Titulo = "Se7en"
                        },
                        new
                        {
                            Id = 27,
                            Ano = 2014,
                            DiretorId = 10,
                            Titulo = "Gone Girl"
                        },
                        new
                        {
                            Id = 28,
                            Ano = 1993,
                            DiretorId = 1,
                            Titulo = "Jurassic Park"
                        },
                        new
                        {
                            Id = 29,
                            Ano = 1982,
                            DiretorId = 1,
                            Titulo = "E.T."
                        },
                        new
                        {
                            Id = 30,
                            Ano = 1993,
                            DiretorId = 1,
                            Titulo = "Schindler's List"
                        },
                        new
                        {
                            Id = 31,
                            Ano = 2002,
                            DiretorId = 1,
                            Titulo = "Catch Me If You Can"
                        },
                        new
                        {
                            Id = 32,
                            Ano = 2004,
                            DiretorId = 1,
                            Titulo = "The Terminal"
                        },
                        new
                        {
                            Id = 33,
                            Ano = 2005,
                            DiretorId = 1,
                            Titulo = "War of the Worlds"
                        },
                        new
                        {
                            Id = 34,
                            Ano = 2015,
                            DiretorId = 3,
                            Titulo = "The Hateful Eight"
                        },
                        new
                        {
                            Id = 35,
                            Ano = 2009,
                            DiretorId = 3,
                            Titulo = "Inglourious Basterds"
                        },
                        new
                        {
                            Id = 36,
                            Ano = 2010,
                            DiretorId = 4,
                            Titulo = "Shutter Island"
                        },
                        new
                        {
                            Id = 37,
                            Ano = 2006,
                            DiretorId = 4,
                            Titulo = "The Departed"
                        },
                        new
                        {
                            Id = 38,
                            Ano = 2004,
                            DiretorId = 4,
                            Titulo = "The Aviator"
                        },
                        new
                        {
                            Id = 39,
                            Ano = 2012,
                            DiretorId = 6,
                            Titulo = "Prometheus"
                        },
                        new
                        {
                            Id = 40,
                            Ano = 2015,
                            DiretorId = 6,
                            Titulo = "The Martian"
                        },
                        new
                        {
                            Id = 41,
                            Ano = 2012,
                            DiretorId = 7,
                            Titulo = "The Hobbit: An Unexpected Journey"
                        },
                        new
                        {
                            Id = 42,
                            Ano = 2013,
                            DiretorId = 7,
                            Titulo = "The Hobbit: The Desolation of Smaug"
                        },
                        new
                        {
                            Id = 43,
                            Ano = 2014,
                            DiretorId = 7,
                            Titulo = "The Hobbit: The Battle of the Five Armies"
                        },
                        new
                        {
                            Id = 44,
                            Ano = 2003,
                            DiretorId = 8,
                            Titulo = "Big Fish"
                        },
                        new
                        {
                            Id = 45,
                            Ano = 2005,
                            DiretorId = 8,
                            Titulo = "Charlie and the Chocolate Factory"
                        },
                        new
                        {
                            Id = 46,
                            Ano = 2014,
                            DiretorId = 9,
                            Titulo = "American Sniper"
                        },
                        new
                        {
                            Id = 47,
                            Ano = 2003,
                            DiretorId = 9,
                            Titulo = "Mystic River"
                        },
                        new
                        {
                            Id = 48,
                            Ano = 2007,
                            DiretorId = 10,
                            Titulo = "Zodiac"
                        },
                        new
                        {
                            Id = 49,
                            Ano = 2010,
                            DiretorId = 10,
                            Titulo = "The Social Network"
                        },
                        new
                        {
                            Id = 50,
                            Ano = 2011,
                            DiretorId = 10,
                            Titulo = "The Girl with the Dragon Tattoo"
                        });
                });

            modelBuilder.Entity("Curso.API.Entities.Filme", b =>
                {
                    b.HasOne("Curso.API.Entities.Diretor", "Diretor")
                        .WithMany("Filmes")
                        .HasForeignKey("DiretorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diretor");
                });

            modelBuilder.Entity("Curso.API.Entities.Diretor", b =>
                {
                    b.Navigation("Filmes");
                });
#pragma warning restore 612, 618
        }
    }
}
